defmodule Mix.Tasks.Beacon.Gen.Safelist do
  @shortdoc "Generates a self-recompiling CSS safelist module"

  @moduledoc """
  Generates a module that automatically extracts and validates Tailwind CSS
  class names from your host app's source files at compile time.

  The generated module uses `__mix_recompile__?/0` to detect when source
  files change and automatically re-extracts classes on the next `mix compile`.

  ## Usage

      mix beacon.gen.safelist --module MyAppWeb.BeaconSafelist --paths "lib/*_web/**/*.ex,lib/*_web/**/*.heex"

  ## Options

    * `--module` - The module name to generate (required)
    * `--paths` - Comma-separated glob patterns for source files to scan (required)
    * `--output` - Output file path (optional, derived from module name by default)

  ## Example

      mix beacon.gen.safelist \\
        --module DockYardWeb.BeaconSafelist \\
        --paths "lib/*_web/components/**/*.ex,lib/*_web/components/**/*.heex,lib/*_web/live/**/*.ex,lib/*_web/live/**/*.heex"

  Then add to your Beacon site config:

      css_safelist_module: DockYardWeb.BeaconSafelist

  The module will automatically recompile when source files change.
  """

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    {opts, _, _} =
      OptionParser.parse(args,
        strict: [module: :string, paths: :string, output: :string]
      )

    module_name = opts[:module] || Mix.raise("--module is required")
    paths_str = opts[:paths] || Mix.raise("--paths is required")

    output_path =
      opts[:output] ||
        module_name
        |> String.replace(".", "/")
        |> Macro.underscore()
        |> then(&"lib/#{&1}.ex")

    content = generate_module(module_name, paths_str)

    output_dir = Path.dirname(output_path)
    File.mkdir_p!(output_dir)
    File.write!(output_path, content)

    Mix.shell().info("Generated #{output_path}")
    Mix.shell().info("")
    Mix.shell().info("The module will automatically extract and validate Tailwind")
    Mix.shell().info("classes from your source files at compile time.")
    Mix.shell().info("")
    Mix.shell().info("Add to your Beacon site config:")
    Mix.shell().info("")
    Mix.shell().info("    css_safelist_module: #{module_name}")
    Mix.shell().info("")
  end

  defp generate_module(module_name, paths_str) do
    ~s'''
    defmodule #{module_name} do
      @moduledoc false
      # Generated by mix beacon.gen.safelist.
      # This module auto-recompiles when source files change.

      @paths ~w[#{paths_str |> String.split(",") |> Enum.map_join(" ", &String.trim/1)}]

      # Expand globs and hash file contents at compile time
      @source_files @paths
                    |> Enum.flat_map(&Path.wildcard/1)
                    |> Enum.uniq()
                    |> Enum.filter(&File.regular?/1)
                    |> Enum.sort()

      @source_hash @source_files
                   |> Enum.map(&File.read!/1)
                   |> :erlang.md5()

      # Extract and validate candidates at compile time
      @candidates (
        tokens =
          @source_files
          |> Enum.flat_map(fn file ->
            file
            |> File.read!()
            |> then(fn content ->
              ~r/class\\s*[=:]\\s*["']([^"']*)["']/i
              |> Regex.scan(content, capture: :all_but_first)
              |> List.flatten()
              |> Enum.flat_map(&String.split/1)
              |> Enum.map(&String.trim/1)
              |> Enum.filter(fn token ->
                byte_size(token) > 1 and
                  String.match?(token, ~r/^[!@a-z\\-\\[]/i) and
                  String.match?(token, ~r/[a-z]/i) and
                  not String.starts_with?(token, "//") and
                  not String.starts_with?(token, "http") and
                  not String.starts_with?(token, "{{") and
                  not String.contains?(token, "==")
              end)
            end)
          end)
          |> Enum.uniq()

        try do
          TailwindCompiler.validate(tokens) |> Enum.sort()
        rescue
          _ -> tokens |> Enum.sort()
        end
      )

      def __mix_recompile__? do
        source_files =
          @paths
          |> Enum.flat_map(&Path.wildcard/1)
          |> Enum.uniq()
          |> Enum.filter(&File.regular?/1)
          |> Enum.sort()

        hash =
          source_files
          |> Enum.map(&File.read!/1)
          |> :erlang.md5()

        hash != @source_hash
      end

      @doc "Returns the list of validated Tailwind CSS candidates from host app source files."
      def list, do: @candidates
    end
    '''
  end
end
