defmodule Mix.Tasks.Beacon.Gen.Safelist do
  @shortdoc "Generates a CSS safelist module from host app source files"

  @moduledoc """
  Extracts Tailwind CSS class names from your host app's source files and
  generates a compiled Elixir module containing only validated class names.

  This ensures that CSS classes used in your Phoenix templates (outside of
  Beacon CMS content) are included in Beacon's CSS compilation.

  ## Usage

      mix beacon.gen.safelist --module MyAppWeb.BeaconSafelist --paths "lib/*_web/**/*.ex,lib/*_web/**/*.heex"

  ## Options

    * `--module` - The module name to generate (required)
    * `--paths` - Comma-separated glob patterns for source files to scan (required)
    * `--output` - Output file path (optional, derived from module name by default)

  ## Example

      mix beacon.gen.safelist \\
        --module DockYardWeb.BeaconSafelist \\
        --paths "lib/*_web/components/**/*.ex,lib/*_web/components/**/*.heex,lib/*_web/live/**/*.ex,lib/*_web/live/**/*.heex,lib/*_web/layouts/**/*.heex,lib/*_web/controllers/**/*.heex"

  The generated module:

      defmodule DockYardWeb.BeaconSafelist do
        @moduledoc false
        # Auto-generated by mix beacon.gen.safelist. Do not edit.

        @candidates ~w[
          antialiased
          bg-white
          hover:bg-blue-50
          md:leading-8
        ]

        def list, do: @candidates
      end

  Add the module to your Beacon site config:

      css_safelist_module: DockYardWeb.BeaconSafelist

  """

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    {opts, _, _} =
      OptionParser.parse(args,
        strict: [module: :string, paths: :string, output: :string]
      )

    module_name = opts[:module] || Mix.raise("--module is required")
    paths_str = opts[:paths] || Mix.raise("--paths is required")
    paths = String.split(paths_str, ",", trim: true) |> Enum.map(&String.trim/1)

    output_path =
      opts[:output] ||
        module_name
        |> String.replace(".", "/")
        |> Macro.underscore()
        |> then(&"lib/#{&1}.ex")

    Mix.shell().info("Scanning source files for Tailwind classes...")

    # Expand globs and read files
    files =
      paths
      |> Enum.flat_map(&Path.wildcard/1)
      |> Enum.uniq()
      |> Enum.filter(&File.regular?/1)

    Mix.shell().info("  Found #{length(files)} source files")

    # Extract raw tokens from class attributes
    tokens =
      files
      |> Enum.flat_map(&extract_tokens/1)
      |> Enum.uniq()

    Mix.shell().info("  Extracted #{length(tokens)} raw tokens")

    # Validate through TailwindCompiler NIF
    Mix.Task.run("app.config")

    valid =
      case TailwindCompiler.validate(tokens) do
        candidates when is_list(candidates) -> Enum.sort(candidates)
        _ -> Mix.raise("TailwindCompiler.validate/1 failed")
      end

    Mix.shell().info("  Validated #{length(valid)} Tailwind class names")

    # Generate module
    content = generate_module(module_name, valid, paths)

    # Write file
    output_dir = Path.dirname(output_path)
    File.mkdir_p!(output_dir)
    File.write!(output_path, content)

    Mix.shell().info("  Generated #{output_path}")
    Mix.shell().info("")
    Mix.shell().info("Add to your Beacon site config:")
    Mix.shell().info("")
    Mix.shell().info("    css_safelist_module: #{module_name}")
    Mix.shell().info("")
  end

  defp extract_tokens(file_path) do
    file_path
    |> File.read!()
    |> extract_from_content()
  end

  defp extract_from_content(content) do
    # Find class="..." and class={...} attributes
    ~r/class\s*[=:]\s*["']([^"']*)["']/i
    |> Regex.scan(content, capture: :all_but_first)
    |> List.flatten()
    |> Enum.flat_map(&String.split/1)
    |> Enum.map(&String.trim/1)
    |> Enum.filter(&valid_token?/1)
  end

  defp valid_token?(token) do
    byte_size(token) > 1 and
      String.match?(token, ~r/^[!@a-z\-\[]/i) and
      String.match?(token, ~r/[a-z]/i) and
      not String.starts_with?(token, "//") and
      not String.starts_with?(token, "http") and
      not String.starts_with?(token, "{{") and
      not String.contains?(token, "==")
  end

  defp generate_module(module_name, candidates, paths) do
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()
    paths_str = Enum.join(paths, ", ")

    candidates_str =
      candidates
      |> Enum.map(&"    #{&1}")
      |> Enum.join("\n")

    """
    defmodule #{module_name} do
      @moduledoc false
      # Auto-generated by mix beacon.gen.safelist. Do not edit.
      # Generated at: #{timestamp}
      # Source paths: #{paths_str}
      # Candidates found: #{length(candidates)}

      @candidates ~w[
    #{candidates_str}
      ]

      def list, do: @candidates
    end
    """
  end
end
