name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'guides/**'
  pull_request:
    paths-ignore:
      - 'guides/**'

permissions:
  contents: write

jobs:
  test:
    name: "test: OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}} | Phoenix ${{matrix.phoenix}} | LV ${{matrix.phoenix-live-view}} | PG ${{matrix.postgres}}"

    strategy:
      fail-fast: false
      matrix:
        include:
          # minimum required versions
          - otp: "23"
            elixir: "1.14.0"
            phoenix: "1.7.0"
            phoenix-live-view: "0.20.2"
            postgres: '13.0-alpine'

          # latest
          - otp: "27"
            elixir: "1.17"
            phoenix: "~> 1.7"
            phoenix-live-view: "~> 1.0"
            postgres: '16.4-alpine'

    env:
      MIX_ENV: test
      PHOENIX_VERSION: ${{matrix.phoenix}}
      PHOENIX_LIVE_VIEW_VERSION: ${{matrix.phoenix-live-view}}

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:${{matrix.postgres}}
        env:
          POSTGRES_DB: beacon_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache mix deps
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: mix-${{ env.MIX_ENV }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ matrix.phoenix}}-${{ matrix.phoenix-live-view}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ env.MIX_ENV }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ matrix.phoenix}}-${{ matrix.phoenix-live-view}}-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get --only-test

      - run: mix tailwind.install

      - name: mix test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{job.services.postgres.ports[5432]}}/beacon_test
        run: mix test

  quality:
    name: "quality: OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}} | Phoenix ${{matrix.phoenix}} | LV ${{matrix.phoenix-live-view}}"

    strategy:
      fail-fast: false
      matrix:
        include:
          # latest
          - otp: "27"
            elixir: "1.17"
            phoenix: "~> 1.7"
            phoenix-live-view: "~> 1.0"

    env:
      MIX_ENV: dev

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache mix deps
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: mix-${{ env.MIX_ENV }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ matrix.phoenix}}-${{ matrix.phoenix-live-view}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ env.MIX_ENV }}-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ matrix.phoenix}}-${{ matrix.phoenix-live-view}}-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: mix compile --warnings-as-errors

      - run: mix deps.unlock --check-unused

      - run: mix credo --strict

      - run: mix assets.setup

      - run: mix format.all

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: auto format code

      - run: mix format.all.check
